services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  caddy:
    image: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/data:/data/
      - ./caddy/config:/config/
      - ./Caddyfile:/etc/caddy/Caddyfile